version: '3.9'
services:
    myapp:
        container_name: app-php
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - '.:/var/www/html'
    nginx:
        container_name: app-nginx
        image: 'nginx:alpine'
        ports:
            - "5000:80"
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ./docker/8.0/nginx/app.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - myapp
            - mysql
            - redis
            - echo_server
    redis:
        container_name: app-redis
        image: redis:alpine
        restart: unless-stopped
        ports:
            - '${REDIS_PORT:-6379}:6379'
        volumes:
            - dbredis:/data
    mysql:
        container_name: app-mysql
        image: 'mysql:8.0'
        ports:
            - '${DB_PORT:-3307}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-root}'
            MYSQL_DATABASE: '${DB_DATABASE:-api_go}'
            MYSQL_USER: '${DB_USERNAME:-user}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        restart: unless-stopped
        volumes:
            - dbmysql:/var/lib/mysql
    echo_server:
        container_name: echo_server
        build:
            context: ./docker/laravel-echo-server
            dockerfile: Dockerfile
        volumes:
            - .env:/app/.env
            - ./docker/laravel-echo-server/laravel-echo-server.json:/app/laravel-echo-server.json
        restart: unless-stopped
    # labview:
    #     container_name: app-labview
    #     image: felipefoz/labview
volumes:
    dbmysql:
        driver: local
    dbredis:
        driver: local
